# Generated by Django 4.1.7 on 2023-03-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(default='AJSNJ1767282'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='certificate',
            field=models.CharField(default='Tashkent, Shayhontohur', max_length=50),
            preserve_default=False,
        ),
    ]
