# Generated by Django 4.1.7 on 2023-03-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_seller_address_seller_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
