# Generated by Django 4.1.7 on 2023-03-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='phone',
        ),
    ]
