# Generated by Django 4.1.7 on 2023-03-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customer_user_alter_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='app.seller'),
        ),
    ]
